# Generated by Django 3.2.13 on 2022-10-20 08:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20221017_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
