# Generated by Django 3.2.13 on 2022-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfolio_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='p_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
