# Generated by Django 3.2.13 on 2022-10-29 12:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='my_image',
            field=models.ImageField(blank=True, upload_to=accounts.models.User.user_image_path),
        ),
    ]
